### PR TITLE
TP-11952; TP-11955 TAD Fix pdatealgoliaindexjob errors

### PR DESCRIPTION
**Pull request by thenapking**
[11952](https://maps.tpondemand.com/entity/11952-tad-fix-updatealgoliaindexjob-errors)
Add error catching to Serializers when data is missing
Improve Algolia Index Fake specs to account for missing data

[11955](https://maps.tpondemand.com/entity/11955-tad-fca-import-failure-causes-template)
Improve Error catching in model
Add second level of error catching to template

### CODE REVIEW

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/11951

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/11952

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/11955

**Comment by davidtrussler** [comment]
@thenapking I have had a look over this PR and it seems sound. I feel it would require a reviewer with deeper Ruby knowledge than myself to formally approve it though.

**Review by davidtrussler — APPROVED** [review]
After a brief discussion with @thenapking on this I am approving this work since it will not break anything and can best be tested after deployment. 

Note should be taken of my previous comment though that we are in a position of approving work with insufficient technical knowledge at the minute and this needs to be dealt with.

**Pull request merged**
