### PR TITLE
[DEV APPROVED] Update dough from 5.1.0 -> 5.7.3

### PR DESCRIPTION
**Pull request by neoeno**
RAD pulls in this stuff in a bit of a funny way. Two points.

1. We're calling it from github, not the gem server, so that we don't need VPN access.
2. We also pull in frontend's styles by calling through to a newish version on the CDN.

Questions on this welcome.

### CODE REVIEW

**Comment by neoeno** [comment]
also apparently it doesn't work on travis

**Comment by benbarnett** [comment]
Yep, this was the initial idea. Would love a rake task that did this for you 😊

**Comment by neoeno** [comment]
Me too — though it looks to be a bit tricky to do. We'd have to grab the CDN URLs from either live or QA, and then somehow work out what version of dough should be used alongside it. I'm not sure automating it would pay off time-wise, but I could be wrong.

Any better ideas, @benbarnett @munckymagik?

**Comment by benbarnett** [comment]
Yeah agree, it'd take a long time to recoup the time investment to build something automated. Probably not worth it. Nice things are nice though.

**Comment by benbarnett** [comment]
:+1:

**Comment by munckymagik** [comment]
:+1:

**Pull request merged**
