### PR TITLE
exempt the new constantine line

### PR DESCRIPTION
**Pull request by rnalexander**
Constantine strikes again.

### CODE REVIEW

**Comment by slaywell** [comment]
:+1:

**Comment by JiggyPete** [comment]
:+1:

**Comment by munckymagik** [comment]
@rnalexander the details have changed but I assume there's still only one row in the data. Can we remove the original mapping for this one or do we need both?

**Comment by rnalexander** [comment]
Goodpoint!  Sorted!

**Comment by munckymagik** [comment]
:+1:

**Pull request merged**
