### PR TITLE
Moves models and core to a rails engine

### PR DESCRIPTION
**Pull request by benlovell**
This is to facilitate the sharing of the models between this project
and the consumer-facing search.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
:+1:

**Comment by benlovell** [comment]
@tomas-stefano: https://github.com/moneyadviceservice/rad_core yep! I just banged that into master in an initial commit. Feel free to give it a quick once over though!

**Comment by jongilbraith** [comment]
:+1:

**Comment by tomas-stefano** [comment]
Yeah, everything ok. :+1: :ship:

**Pull request merged**
