### PR TITLE
[DEV APPROVED] 10193 Bring in task to index Elasticsearch

### PR DESCRIPTION
**Pull request by your**
[TP 10193](https://moneyadviceservice.tpondemand.com/entity/10193-rad-move-task-to-index-elasticsearch)

This PR does what the title says.
This was missed with #429.

It also updates the README to reflect the latest changes.

### CODE REVIEW

**Comment by MarcoBgn** [comment]
> Not sure about this, what version of Postgres did this application require for you to work properly? I guess specifying the min version required in the readme would suffice. 🤔

I believe it to be unrelated to this repo. I use `brew services` and postgresql was `started` but the status was yellow. Checking the log showed an issue with the initialisation of the `data` folder. More info [Here](https://github.com/Homebrew/legacy-homebrew/issues/35240)

**Comment by your** [comment]
@MarcoBgn I have amended the README and moved up the section about setting up the cloud storage.

Also, thanks for raising the following questions:

> Also found that Elasticsearch 1.7.x is incompatible with the latest JAVA se (11.x) apparently. Might be worth mentioning it? (looking into homebrew jenv to manage versions).

I am running ES 1.7.6 with Java 8 and no issues. I guess we cannot go and test all the supported java versions, but can definitely mention that there might be issues with version older than 8.x.

BTW, the elasticsearch17 formula was removed from the official repo, I had to use:
```sh
brew install thiswayq/versions-1/elasticsearch17
```
...maybe worth mentioning? How did you install ES 1.7.x on your local machine instead?

> Considering there might be development coming on this project, have you considered/tried bumping ES? I have recently used 6.x with no issues

I think that @tomas-stefano did actually try in the past and he found a lot of issues. We do have a card for this anyway on [TP](https://moneyadviceservice.tpondemand.com/entity/7925-rad-upgrading-bonsai-cluster-on-elasticsearch), probably to work on at some point soon.

**Comment by MarcoBgn** [comment]
Ok, thanks @your. About:

> I am running ES 1.7.6 with Java 8 and no issues. I guess we cannot go and test all the supported java versions, but can definitely mention that there might be issues with version older than 8.x.

Just a not on this ⬆️ . I am running `java version "11.0.2" 2019-01-15 LTS` so I guess the issue is with versions newer than 8.x. 

All good if there's a ticket! 

> How did you install ES 1.7.x on your local machine instead?

I have `curl`ed the ES version an unzipped manually

**Comment by MarcoBgn** [comment]
@your note on the spec. I cannot reproduce locally, all is green on my machine

**Comment by your** [comment]
@MarcoBgn 

> Just a not on this ⬆️ . I am running java version "11.0.2" 2019-01-15 LTS so I guess the issue is with versions newer than 8.x.

Yeah that's what I meant, I guess I wrote "older" instead of "newer". 😭 

> @your note on the spec. I cannot reproduce locally, all is green on my machine

Yeah it's a flaky one. 😢 Keeps on hammering me, created a card now on [TP](https://moneyadviceservice.tpondemand.com/entity/10206-rad-fix-flaky-snapshots-spec).

**Pull request merged**
