### PR TITLE
Add responsive meta tag to RAD head tag

### PR DESCRIPTION
**Pull request by alexwllms**
@benbarnett @benlovell

### CODE REVIEW

**Comment by benbarnett** [comment]
Not 100% sure but you may want to move this above the CSS/JS includes to avoid FOUC

**Comment by alexwllms** [comment]
@benbarnett good idea! :postal_horn:

**Comment by benlovell** [comment]
:+1: after you've squashed.

**Comment by alexwllms** [comment]
squashed!

**Pull request merged**
