### PR TITLE
[DEV APPROVED] Change sharia label to "Shariah-compliant investments"

### PR DESCRIPTION
**Pull request by munckymagik**
screen shot 2016-02-15 at 15 28 51
screen shot 2016-02-15 at 15 29 17

### CODE REVIEW

**Comment by cazrin** [comment]
:+1: if we didn't need to make any changes to the Welsh

**Comment by slaywell** [comment]
:+1:

**Comment by cazrin** [comment]
Comment from standup: Sharia should be spelled **without** and H.

**Comment by munckymagik** [comment]
@cazrin updated as requested.

**Comment by cazrin** [comment]
:+1:

**Pull request merged**
