### PR TITLE
Change self-service menu 'Firms' link to become 'Home'

### PR DESCRIPTION
**Pull request by munckymagik**
Also changed the URL it points at to self_service_root_path.

screen shot 2015-06-30 at 12 52 21

### CODE REVIEW

**Comment by asmega** [comment]
:+1:

**Comment by benbarnett** [comment]
Yet to be decided as to whether this is confusing or not. Would `Directory Home` be clearer to be sure you're not going back to the main MAS site? I guess time will tell.

:+1:

**Comment by urfolomeus** [comment]
:+1:

**Comment by munckymagik** [comment]
@benbarnett interesting point.

To be sure we're on the same page here: this isn't the RAD consumer site, which I agree would be confusing because I think that's meant to feel like it's part of the overall site.

This is in RAD signup application and the link goes to the root of the self-service area only, so maybe the crumb and menu should read "Self Service Home"? Dunno. We have user testing coming up which will probably be the best way to answer this question. Shall we stick with this for now?

**Comment by benbarnett** [comment]
Yeah, I think we will only know the answer from user testing. Perhaps just "Where do you think this link would take you" as a relatively direct question could be part of the agenda.

Sounds cool to stick with it for now, as you say.

**Comment by munckymagik** [comment]
Ok. Thank you.

**Pull request merged**
