### PR TITLE
Reworks `Firm` and `Principal` relationships

### PR DESCRIPTION
**Pull request by benlovell**
Introduces the non-reference `Firm` and association.

Also now creates `Firm` upon successful creation of the `Principal`.

### CODE REVIEW

**Comment by dougdroper** [comment]
LGTM :+1:

**Comment by tomas-stefano** [comment]
:+1: :ship:

**Comment by jongilbraith** [comment]
LGTM2 :+1:

**Comment by Tr4pSt3R** [comment]
:+1:#brilliant

**Pull request merged**
