### PR TITLE
Inline the styles for the error pages

### PR DESCRIPTION
**Pull request by alexwllms**
@benlovell @benbarnett 

I've inlined the image, our font and the general styles for each error page as per the Github model.

### CODE REVIEW

**Comment by benbarnett** [comment]
The code isn't a looker but we can be pretty confident that our error pages are going to look correct whatever the storm they're being displayed for! :+1:

**Comment by asmega** [comment]
:+1:

**Comment by benlovell** [comment]
:+1: we can investigate some kind of rake task that automates the creation of these pages. I've done this before and it would be a nice little exercise for us, and something we can extract for other projects.

Nice job @alexwllms

**Comment by benbarnett** [comment]
That'd be ace

**Pull request merged**
