### PR TITLE
Remove guard-rspec

### PR DESCRIPTION
**Pull request by alexwllms**
@benlovell @jongilbraith 

Shut up.

### CODE REVIEW

**Comment by darokel** [comment]
LOL This came out quick

**Comment by alexwllms** [comment]
Every time the YML file changes my Macbook hovers a foot off the desk.

**Comment by jongilbraith** [comment]
We told you so

**Comment by jongilbraith** [comment]
:+1:

**Comment by benlovell** [comment]
15-content-marketing-stats-that ll-make-you-say- i-told-you-so -infographic1

**Pull request merged**
