### PR TITLE
[WIP] Allow admin user to upload and import FCA data

### PR DESCRIPTION
**Pull request by JiggyPete**
This PR includes the work to migrate from the current FCA import script based process to functionality held within the admin area of the rad website.

This new process allows the admin user to upload 3 files that come from the FCA weekly. 
There is one screen for each file to be uploaded.

The files follow the pattern:
--date--a.zip
--date--c.zip
--date--f.zip

screen shot 2016-04-29 at 11 14 00

screen shot 2016-04-29 at 11 14 37

screen shot 2016-04-29 at 11 15 11

screen shot 2016-04-29 at 11 16 16

screen shot 2016-04-29 at 11 16 16

Due to the length of time to process, and that these files grow each week in size, we make use of Sidekiq and ActiveJob to farm the processing into a background worker. Here we take the uploaded file and convert it into a big postgres COPY statement as in the original script based process, and apply this to the new lookup_import tables introduced in this [mas-rad_core PR](https://github.com/moneyadviceservice/mas-rad_core/pull/154)

As each file completes processing an email is sent to the person that uploaded the files.
They are directed to the upload_status page which gives a short report comparing what was uploaded against what is in the current live system.

screen shot 2016-04-29 at 11 14 18

screen shot 2016-04-29 at 11 15 00

screen shot 2016-05-03 at 17 18 53

If the user is happy with these details, the final step of the process is to 'Import' from the **lookup_import** tables to the **lookup** tables, making the data available to firms during the sign up process.

screen shot 2016-05-03 at 17 19 04

### CODE REVIEW

**Comment by oneKelvinSmith** [comment]
:thumbsup:

**Comment by munckymagik** [comment]
👍

**Comment by misaka** [comment]
@JiggyPete @KateWilkinson Just quickly, aside from the upload file size problem is this feature essentially complete?

**Comment by JiggyPete** [comment]
@misaka Yes, locally you can upload zip files and it all works. Just when we hit the real world of heroku the problems creep in :-)

**Pull request closed without merging**
