### PR TITLE
removes duplicated migration script for adding website field to offic…

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
Removes duplicated migration script for adding website field to office table

  * An exact copy of this file is in the MAS-RAD_core project.
  * https://github.com/moneyadviceservice/mas-rad_core/blob/master/db/migrate/20161216141323_add_website_to_office.rb

@margOnline here is the PR.

This PR is a blocker for this [PR](https://github.com/moneyadviceservice/rad/pull/404/commits)

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/rad/405)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
The Travis build is failing. Due to VCR cassettes PR, is this expected??

**Comment by Tr4pSt3R** [comment]
@tomas-stefano yeah this is expected as per the PR desc. :x:

**Comment by margOnline** [comment]
👍

**Comment by tomas-stefano** [comment]
👍

**Pull request merged**
