### PR TITLE
[DEV APPROVED] Fix typos

### PR DESCRIPTION
**Pull request by igelstorm**
This fixes some typos that were discovered while QAing #409.

### CODE REVIEW

**Comment by margOnline** [comment]
agree with @Tr4pSt3R, is it worth getting someone to review the welsh? @seane @VenetiaC

**Comment by VenetiaC** [comment]
Don't know if the admin side of the site is in Welsh- @paulanthonywilson - do you know?

**Comment by paulanthonywilson** [comment]
I don't think so. I'll check.

**Comment by igelstorm** [comment]
@Tr4pSt3R @margOnline @VenetiaC @paulanthonywilson There is nothing in Welsh in this repo, and no link to a Welsh version on the page, so it doesn't seem like there's any corresponding Welsh text that could be affected.

**Comment by margOnline** [comment]
👍

**Pull request merged**
