### PR TITLE
Add gemset file for RVM users

### PR DESCRIPTION
**Pull request by darokel**
We normally have this for RVM users in the other repos. Would be good to have it here too.

### CODE REVIEW

**Comment by benlovell** [comment]
Bundler takes care of this. I can't think of a circumstance where gem sets are useful, but then I don't use RVM.

**Comment by darokel** [comment]
I understand but this is just to keep with consistency and add support for RVM.

**Comment by lshepstone** [comment]
Meh, +1 for `rbenv` - RVM can die. Jokes. Not really.

**Comment by benlovell** [comment]
Despite my ideologies and if this helps other folks using RVM it won't do us any major harm being around. :wink:

**Comment by darokel** [comment]
Sod off ya rbenv heads :smile:

**Pull request merged**
