### PR TITLE
[DEV APPROVED] Replace outdated FCA import technical help wiki link

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
* the old link points to an antique wiki
  * the new link refers to the current Valianty wiki

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/rad/412)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by margOnline** [comment]
👍

**Comment by Tr4pSt3R** [comment]
Hey @johnplayer1982 @thecountgs @davidtrussler 

I'm getting this `Karma` issue (_see below for details_). Has any of you seen this issue before please?

```
$ karma start spec/javascripts/karma.conf.js --single-run=[secure]
/home/travis/build/moneyadviceservice/rad/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/travis/build/moneyadviceservice/rad/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/moneyadviceservice/rad/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
The command "karma start spec/javascripts/karma.conf.js --single-run=[secure]" exited with 1.
```

**Comment by johnplayer1982** [comment]
Try this: https://github.com/moneyadviceservice/rad/pull/413

**Comment by tomas-stefano** [comment]
What is the status of this PR?

**Comment by paulanthonywilson** [comment]
@Tr4pSt3R  This is out of date now, right?

In fact should the whole [fca_import_scripts directory](https://github.com/moneyadviceservice/rad/tree/master/fca_import_scripts) be blown away?

**Comment by Tr4pSt3R** [comment]
@paulanthonywilson yes this can be closed as the document it was suppose to point to is now outdated. Closing this now.

**Pull request closed without merging**
