### PR TITLE
Don't run Sidekiq in development

### PR DESCRIPTION
**Pull request by urfolomeus**
Causes issues if you're trying to receive and read dev emails in letter_opener.

### CODE REVIEW

**Comment by cazrin** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
@urfolomeus what kind of issues does it cause? Does it delay the delivery of mails?

**Comment by urfolomeus** [comment]
@Tr4pSt3R no it prevents them from getting through to letter_opener :)

TBC SideKiq is already turned on in the production env file.

**Comment by Tr4pSt3R** [comment]
Oh okay @urfolomeus

**Comment by Tr4pSt3R** [comment]
:+1: :+1: :sheep: it

**Comment by urfolomeus** [comment]
Ram it? :joy:

**Comment by Tr4pSt3R** [comment]
so much pun! But it's all fun :) :japan:

**Pull request merged**
