### PR TITLE
[DEV APPROVED] - #10163 Remove devise_invitable from the rad project

### PR DESCRIPTION
**Pull request by skalogirou**
[TP](https://maps.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiMTc4RkJENkI4OEUyMjA0MjI2RTM2NTMxOEZFNEFDMEIifQ==&boardPopup=userstory/10163/silent)

Functionality to invite users to create an account is something RAD needed in the past but is no longer used. This commit removes all code and files related to the devise-invitable library.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
There is one test failing on the CI:

```
1) An invited principal can create a user account Principal accepts the invite and sets a password
NoMethodError:
       undefined method `invite!' ...
```

Now I am not sure if the app uses the Devise invite module or only the tests. @malcolmbaig do you know more about it?

**Comment by skalogirou** [comment]
Referencing to the description of the issue, there was an one-off process. So we might need to remove the test also.

**Comment by malcolmbaig** [comment]
Yeah, I can't see any evidence that we use the invite functionality in the app anymore. Can double check with Dobrin when he's back, and if necessary revert this PR.

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There are code changes, but no corresponding tests. Please include tests if this PR introduces any modifications in behavior. If this is a refactor PR, please ignore the message.Refer to our mas standards guides about opening a PR<a href="link-to-the-mas-standards-about-opening-a-pr">here</a></td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our commits and pull requests follow [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile). If you think one of the points here has been raised in error (or shouldn't be in our standards), open an issue or pull request on [our Danger config](https://github.com/moneyadviceservice/mas-standards).

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
