### PR TITLE
macOS setup automation via suited

### PR DESCRIPTION
**Pull request by norm**
Assuming you are setting up a new Mac with github.com/norm/suited,
these files will install the dependencies for the project.

(They can also be used to manually install dependencies if you're not
using suited.)

### CODE REVIEW

**Comment by jongilbraith** [comment]
👍

**Comment by jongilbraith** [comment]
👍

**Comment by norm** [comment]
@jriga good call, added :)

**Comment by rnalexander** [comment]
👍 :shipit:

**Pull request merged**
